version: '3'

services:
  echoapp:
    build: .
    ports:
      - "3000:3000"
    mem_limit: 256m
    cpu_shares: 512
    environment:
      GIN_MODE: release
  
    volumes:
      - .:/app
    command: go run app/main.go -b 0.0.0.0