version: "3.8"

services:

  db:  
    image: postgres  
    environment:  
      - POSTGRES_USER=user  
      - POSTGRES_PASSWORD=password  
      - POSTGRES_DB=db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data   
    
  goapp:        
    build: .  
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: go run cmd/main.go -b 0.0.0.0
    depends_on: 
      - db